
#pragma once

#include <stdio.h>
#include <tchar.h>


#include <iostream>
#include <stdlib.h>
#include <fstream>
#include <string>
#include <stack>
#include "Core.h"
#include <map>
#include <set>
#include "Exception.h"

#define CELL 81
#define MAX_N 10000
#define	MAX_C 1000000
#define MAX_S 1000000
// InputHandler return
#define ERROR 0
#define C_CMD 1
#define S_CMD 2
#define NM_CMD 3
#define NR_CMD 4
#define NU_CMD 5
#define NRU_CMD 6
// -m
#define EASY 1
#define MIDDLE 2
#define HARD 3

#define BUFFER_SIZE 165

// -r
#define EMPTY_UPPER 55
#define EMPTY_LOWER 20
using namespace std;

#define GRIDSIZE 9
#define UNKNOWN 0
#define SQRTSIZE 3

const string usage = "Usage:";
const string usageC = "sudoku.exe -c <number>";

const string usageS = "sudoku.exe -s <path>";
const string usageN = "sudoku.exe -n <number> -u";

const string usageNM = "sudoku.exe -n <number> -m <mode>";
const string usageNRU = "sudoku.exe -n <number> -r <lower>~<upper> [-u]";

const string commands = "Commands:";
const string commandC = "-c     generate sudoku, <number> = the number of sudoku you want to generate, 1 <= <number> <= 100,0000";
const string commandS = "-s     solve sudoku puzzles, <path> = the path of the sudoku puzzles file";
const string commandN = "-n     generate sudoku puzzles, <number> = the number of sudoku puzzles you want to generate, 1 <= <number> <= 1,0000";

const string commandM = "-m     decides the mode of the sudoku puzzles generated by -n, 1 <= <mode> <= 3 (1:EASY, 2:MIDDLE, 3:HARD)";
const string commandR = "-r     decides the number of the space your sudoku puzzles have, 20 <= <lower> <= the number of the space <= <upper> <= 55";

const string commandU = "-u     make sure the solution of each of your sudoku puzzle is unique";
